server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  log_level: "info"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: false
    max_age: 86400
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst_size: 10
    cleanup_interval: "1m"

database:
  host: "localhost"
  port: 5432
  name: "goforward"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_connections: 25
  max_idle_connections: 5
  max_lifetime: "1h"

auth:
  jwt_secret: "your-secret-key-change-this-in-production"
  jwt_expiration: "24h"
  refresh_expiration: "168h" # 7 days
  otp_expiration: "10m"
  password_min_length: 8
  enable_email_auth: true
  enable_phone_auth: true
  enable_username_auth: true
  require_verification: false
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    from: "noreply@yourapp.com"
    use_tls: true
  sms:
    provider: "twilio"
    twilio:
      account_sid: "your-twilio-account-sid"
      auth_token: "your-twilio-auth-token"
      from_number: "+1234567890"

storage:
  provider: "local" # local or s3
  local_path: "./storage"
  max_file_size: 10485760 # 10MB
  s3:
    region: "us-east-1"
    bucket: "your-bucket"
    access_key_id: "your-access-key"
    secret_access_key: "your-secret-key"
    endpoint: ""
    use_ssl: true

realtime:
  enabled: true
  max_connections: 1000
  heartbeat_interval: "30s"
  read_buffer_size: 1024
  write_buffer_size: 1024
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

dashboard:
  enabled: true
  path: "/admin"
  static_dir: "./dashboard/dist"

logging:
  level: "info"
  format: "json" # json or text
  output: "stdout" # stdout or file
  file_path: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days